### ISSUE TITLE
Clients see different colors for same car

### ISSUE THREAD

**Issue by darkgrue** [FatLurch/TSOG#19]
Watch item for base game enhancement. Not clear if scripting can work-around this issue:

https://forums.bistudio.com/forums/topic/207741-clients-see-different-colours-for-same-car/

**Comment by FatLurch** [comment]
The built in randomize function that BIS uses invokes [setObjectTextureGlobal](https://community.bistudio.com/wiki/setObjectTextureGlobal) which is supposed to sync the colors to all clients. It looks like they figured out how to break something that worked previously...

Ref. code examples from KK: [Link](http://killzonekid.com/arma-annoyances-say-no-to-randomize/)
